### ISSUE TITLE
Underscore missing in path

### ISSUE THREAD

**Issue by GregTrevellick** [lancelot-coder-chen/file-encoding-info-vsext#1]
If the file path contains an underscore then the underscore is not shown.

In the screenshot are your file info and the file info below from a different vsix extension which shows the underscore.

![image](https://user-images.githubusercontent.com/13434709/55991614-940f5180-5ca2-11e9-93ea-995040253834.png)

**Comment by robin88chen** [comment]
Fixed at commit 057ff45227ec6cf66b3d908fa0637a40a9a68463
