### ISSUE TITLE
Info missing for a file

### ISSUE THREAD

**Issue by GregTrevellick** [lancelot-coder-chen/file-encoding-info-vsext#2]
I have the attached file which doesn't show the file info or encoding info in VS2017 (I have not tried in VS2019).

[proguard.cfg.txt](https://github.com/lancelot-coder-chen/file-encoding-info-vsext/files/3071993/proguard.cfg.txt)

I had to add .txt to the name to be able to upload to GitHub so you should change the file back to .cfg type.

The file info in screen grab below for this file is from another extension, and you can see it does not display your vsix information:
![image](https://user-images.githubusercontent.com/13434709/56018724-c77dca80-5cfa-11e9-8dcd-c8c69e55f279.png)

This is an example of your vsix showing correct info (with underscore fixed - thanks!) aswell as info from the other extension:
![image](https://user-images.githubusercontent.com/13434709/56018759-e1b7a880-5cfa-11e9-9f8b-b30d6845fb14.png)

**Comment by robin88chen** [comment]
fixed at commit f2f69095a552edc393b9e7acea2c964f7a57fe75

thanks.
